export enum Icons {
  call = 'call',
  call_blue = 'call_blue',
  bag = 'bag',
  fire = 'fire',
  ring = 'ring',
  ring_red = 'ring_red',
  close = 'close',
  compare = 'compare',
  compare_checked = 'compare_checked',
  heart = 'heart',
  heart_red = 'heart_red',
  arrow_right = 'arrow_right',
  sort = 'sort',
  price_type = 'price_type',
  filter = 'filter',
  badge_blue = 'badge_blue',
  badge_green = 'badge_green',
  badge_yellow = 'badge_yellow',
  badge_purple = 'badge_purple',
  badge_red = 'badge_red',
  badge_gray = 'badge_gray',
  badge_cyan = 'badge_cyan',

  icAnalytics = 'ic_analytics',
  icCart = 'ic_cart',
  icEcommerce = 'ic_ecommerce',
  icKanban = 'ic_kanban',
  icUser = 'ic_user',
  icChat = 'ic_chat',
  icAvatar = 'ic_avatar',
  icCopy = 'ic_copy',
  icNotifications = 'ic_notifications',
  facebook = 'facebook',
  line = 'line',
  skype = 'skype',
  notice = 'notice',
  phone = 'phone',
  account = 'account',
  favorite = 'favorite',
  cart = 'cart',
  iOrder = 'iOrder',
  trash_can = 'trash_can',
  gold = 'gold',
  silver = 'silver',
  bronze = 'bronze',
  home = 'home',
  menu = 'menu',
  info = 'info',
  security = 'security',
  circle_check_solid = 'circle_check_solid',
  memberCenterBankAccount = 'member_center_bank_account',
  memberCenterAccounts = 'member_center_accounts',
  memberCenterDelivery = 'member_center_delivery',
  memberCenterPassword = 'member_center_password',

  memberCenterPoint = 'member_center_point',
  memberCenterGift = 'member_center_gift',
  memberCenterFavorite = 'member_center_favorite',
  memberCenterNotification = 'member_center_notification',

  memberCenterOrder = 'member_center_order',
  memberCenterPriceType = 'member_center_price_type',
  memberCenterAddressPreset = 'member_center_address_preset',
  memberCenterNote = 'member_center_note',
  memberRecent = 'member_recent',
  memberCs = 'member_cs',

  companyPhone = 'company_phone',
  companySkype = 'company_skype',
  companyLine = 'company_line',
  companyEmail = 'company_email',
  add = 'add',
  minus = 'minus',

  current_order = 'current_order',
  current_search = 'current_search',
  current_tally = 'current_tally',
  current_delivery = 'current_delivery',

  not_reached_search = 'not_reached_search',
  not_reached_tally = 'not_reached_tally',
  not_reached_delivery = 'not_reached_delivery',
  not_reached_address = 'not_reached_address',

  order_achieve = 'order_achieve',
  order_search = 'order_search',
  order_tally = 'order_tally',
  order_delivery = 'order_delivery',
  order_address = 'order_address',
  order_cancel = 'order_cancel',

  product_cart = 'product_cart',
  product_CS = 'product_CS',
  product_search = 'product_search', // Added by Kelsier on 2025/01/24 for AR:20250020
  product_notification = 'product_notification',
  product_remove = 'product_remove',

  toggle_on = 'toggle_on',
  toggle_off = 'toggle_off',

  refresh = 'refresh',
  type_grid = 'type_grid',
  type_list = 'type_list',

  ic_compare = 'ic_compare',
  ic_subtract = 'ic_subtract',
  warning = 'warning',
  blue_phone = 'blue_phone',
  blue_skype = 'blue_skype',
  blue_line = 'blue_line',
  blue_email = 'blue_email',

  help = 'help',
  vector_stroke = 'vector_stroke',

  to_the_top = 'to_the_top',

  alarm = 'alarm',

  shopping_cart = 'shopping_cart',
}
