export const environment = {
  production: false,
  enableLogging: false,
  baseApiUrl: 'http://localhost',
  orgId: 83,
  siteKey: '6LfClXcpAAAAAJfoD0pXu6uTdSZ5FukwqzVjR19V',
  rememberMeKey: '-rememberme',
  googleAnalyticsKey: 'G-7L1TQ70F7Z',
  loginGuide: [
    {
      type: 'link',
      title: '線上報修',
      hint: ' 提供網站報修服務 ',
      theme: 'maintenance',
      url: 'https://www.unitech.com.tw/login.aspx',
    },
    {
      type: 'link',
      title: '精技電腦',
      hint: ' 提供完整的服務 ',
      theme: 'office-building',
      url: 'https://www.unitech.com.tw',
    },
    {
      type: 'link',
      title: '精豪電腦',
      hint: ' Apple 獨家專區 ',
      theme: 'i-mac',
      url: 'https://io2ts.unitech.com.tw:8082',
    },
    {
      type: 'modal',
      title: '經銷商專區',
      hint: ' 提供更多資訊服務 ',
      theme: 'files',
      modal: {
        title: ' 經銷商專區需先登入 iOrder',
        text: ' 登入 iOrder 後即可進入經銷商專區。',
        displayFooter: true,
        confirmButton: '確認',
      },
    },
  ],
  fireBaseConfig: {
    apiKey: '',
    authDomain: '',
    databaseURL: 'https://localhost',
    projectId: '',
    storageBucket: '',
    messagingSenderId: '',
    appId: '1:',
    measurementId: '',
  },
};
