name: Jingho CI/CD

env:
  APP_PATH: dist/jingho-web/browser
  
on:
  workflow_run:
    workflows: ["iOrder CI/CD"]
    types:
      - completed

jobs:
  build:
    runs-on: little-box
    if: ${{ github.event.workflow_run.conclusion == 'success' }} # 精技環境 ci/cd 成功才可以執行

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci --no-audit

      - name: Build Dev Iorder
        run: npm run build:jingho:dev

      - name: Upload files via SFTP
        env:
          SFTP_ADDRESS: ${{ secrets.DEV_IP }}
          SFTP_USER: 'gannaDev'
          REMOTE_PATH: '/C:/inetpub/wwwroot/Jingho/DEV/Web' 
          LOCAL_PATH: ${{ env.APP_PATH }}
          SSHPASS: ${{ secrets.SFTP_PASSPHRASE }}
        run: |
          sshpass -e sftp "$SFTP_USER@$SFTP_ADDRESS:$REMOTE_PATH" <<< $"put -r $LOCAL_PATH/*"
